<?php

use Illuminate\Database\Seeder;

class InterpretationTableSeeder extends Seeder {

    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run() {
        DB::unprepared("
        INSERT INTO `fi_overall_range` (`id`, `min_range`, `max_range`,`summary`, `status`, `created_at`, `updated_at`) VALUES
(1, 0,  10,'ADVENTERURE',   '1',    '2019-02-06 05:44:38',  '2019-02-06 05:44:38'),
(2, 10, 20,'ADVOCATE',  '1',    '2019-02-06 05:44:43',  '2019-02-06 05:44:43'),
(3, 20, 30,'ARCHITECT', '1',    '2019-02-06 05:45:04',  '2019-02-06 05:45:04'),
(4, 30, 40,'ARCHITECTS',    '1',    '2019-02-06 05:45:10',  '2019-02-06 05:45:10'),
(5, 40, 50,'COMMANDER', '1',    '2019-02-06 05:45:17',  '2019-02-06 05:45:17'),
(6, 50, 60,'CONSULTANT',    '1',    '2019-02-06 05:45:23',  '2019-02-06 05:45:23'),
(7, 60, 70,'DEBATER',   '1',    '2019-02-06 05:45:30',  '2019-02-06 05:45:30'),
(8, 70, 80,'DEFENDER',  '1',    '2019-02-06 05:45:36',  '2019-02-06 05:45:36'),
(9, 80, 90,'ENTERPRENEUR',  '1',    '2019-02-06 05:45:42',  '2019-02-06 05:45:42'),
(10,    90, 100,'ENTERTAINER',  '1',    '2019-02-06 05:45:49',  '2019-02-06 05:45:49');
");

        DB::unprepared("
             INSERT INTO `fi_over_all_interpretations` (`id`, `category_ids`, `individual_range_ids`, `overall_range`, `interpretation`, `status`, `created_at`, `updated_at`) VALUES
(1, '1,2,3',    '1,1,1',    '1',    '[\"Architect lonely at the top, and being one of the rarest and most strategically capable personality types.\",\"Architect form just two percent of the population, and women of this personality type are especially rare, forming just 0.8% of the population.\",\"Architect enjoy sharing what they know as well, confident in their mastery of their chosen subjects.\",\"Architect at times it will seem that architect are bent on deconstructing and rebuilding every idea and system they come into contact with, employing a sense of perfectionism and even morality to this work.\"]', '1',    '2019-02-06 12:22:53',  '2019-02-07 12:45:48'),
(2, '1,2,3',    '6,3,3',    '4',    '[\"Logician personality type is fairly rare, making up only three percent of the population, which is definitely a good thing for them\",\"Logician are known for their brilliant theories and unrelenting logic  in fact, they are considered the most logically precise of all the personality types\",\"Logician may appear to drift about in an unending daydream, but INTPs thought process is unceasing, and their minds buzz with ideas from the moment they wake up\",\"Logician personalities are so prone to reassessing their own thoughts and theories, worrying that theyve missed some critical piece of the puzzle, that they can stagnate, lost in an intangible world where their thoughts are never truly applied\"]',    '1',    '2019-02-06 12:53:54',  '2019-02-07 12:57:39'),
(3, '1,2,3',    '3,6,3',    '4',    '[\"Commander with this personality type embody the gifts of charisma and confidence, and project authority in a way that draws crowds together behind a common goal.\",\"Commander emotional expression isn\\u2019t the strong suit of any Analyst type, but because of their Extraverted (E) nature, commander distance from their emotions is especially public, and felt directly by a much broader swath of people\",\"Commander need to remember though, that their stature comes not just from their own actions, but from the actions of the team that props them up, and that it\\u2019s important to recognize the contributions\",\"Commander will be rewarded with deep, satisfying relationships and all the challenging victories they can handle\"]',    '1',    '2019-02-06 12:54:43',  '2019-02-07 13:04:58'),
(4, '1,2,3',    '1,1,4',    '2',    '[\"Debater personality type is the ultimate devils advocate, thriving on the process of shredding arguments and beliefs and letting the ribbons drift in the wind for all to see\",\"Debater capacity for debate can be a vexing one  while often appreciated when its called for, it can fall painfully flat when they step on others toes by say, openly questioning their boss in a meeting, or picking apart everything their significant other says\",\"Debater intellectual independence and free-form vision are tremendously valuable when theyre in charge, or at least have the ear of someone\",\"Debater people with this personality type may find that the most complex and rewarding intellectual challenge is to understand a more sentimental perspective, and to argue consideration and compromise alongside logic and progress\"]',   '1',    '2019-02-06 13:28:49',  '2019-02-07 13:08:32'),
(5, '1,2,3',    '1,2,3',    '2',    '[\"Mediator personalities are true idealists, always looking for the hint of good in even the worst of people and events, searching for ways to make things better\",\"Mediator comprising just 4% of the population, the risk of feeling misunderstood is unfortunately high for the INFP personality type  but when they find like-minded people to spend their time with, the harmony they feel will be a fountain of joy and inspiration\",\"Mediator qualities enable INFPs to communicate deeply with others, easily speaking in metaphors and parables, and understanding and creating symbols to share their ideas\",\"Mediator strength of this intuitive communication style lends itself well to creative works, and it comes as no surprise that many famous INFPs are poets, writers and actors\"]', '1',    '2019-02-06 13:30:34',  '2019-02-07 13:12:11'),
(6, '1,2,3',    '1,3,2',    '2',    '[\"Enterperneur personality types always have an impact on their immediate surroundings  the best way to spot them at a party is to look for the whirling eddy of people flitting about them as they move from group to group\",\"Enterperneur laughing and entertaining with a blunt and earthy humor, ESTP personalities love to be the center of attention\",\"Enterperneur is an audience member is asked to come on stage, ESTPs volunteer  or volunteer a shy friend\",\"Enterperneur leap before they look, fixing their mistakes as they go, rather than sitting idle, preparing contingencies and escape clauses\"]',   '1',    '2019-02-06 13:30:40',  '2019-02-07 13:15:00'),
(7, '1,2,3',    '1,4,1',    '2',    '[\"Adventurer personality types are true artists, but not necessarily in the typical sense where theyre out painting happy little trees. Often enough though, they are perfectly capable of this\",\"Adventurer enjoy upsetting traditional expectations with experiments in beauty and behavior  chances are, theyve expressed more than once the phrase \'Dont box me in!\'\",\"Adventurer live in a colorful, sensual world, inspired by connections with people and ideas\",\"Adventurer personalities take joy in reinterpreting these connections, reinventing and experimenting with both themselves and new perspectives\"]',  '1',    '2019-02-06 13:30:45',  '2019-02-07 13:18:17'),
(8, '1,2,3',    '2,1,3',    '2',    '[\"Entertrainer is to be found spontaneously breaking into song and dance, it is the Entertrainer personality type\",\"Entertrainer get caught up in the excitement of the moment, and want everyone else to feel that way, too\",\"Entertrainer enjoy the simplest things, and theres no greater joy for them than just having fun with a good group of friends\",\"Entertrainer  rely on luck or opportunity, or simply ask for help from their extensive circle of friends\"]',    '1',    '2019-02-06 13:30:50',  '2019-02-07 13:21:03'),
(9, '1,2,3',    '2,2,2',    '2',    '[\"Defender personality type is quite unique, as many of their qualities defy the definition of their individual traits\",\"Defender possessing the Feeling (F) trait, Defender have excellent analytical abilities; though Introverted (I), they have well-developed people skills and robust social relationships\",\"Defender are true altruists, meeting kindness with kindness-in-excess and engaging the work and people they believe in with enthusiasm and generosity\",\"Defender need to know when to say no and stand up for themselves if they are to maintain their confidence and enthusiasm\"]',    '1',    '2019-02-06 13:30:55',  '2019-02-07 13:23:49'),
(10,    '1,2,3',    '2,3,1',    '2',    '[\"Advocate personality type is very rare, making up less than one percent of the population, but they nonetheless leave their mark on the world\",\"Advocate have an inborn sense of idealism and morality, but what sets them apart is the accompanying Judging trait\",\"Advocate tend to see helping others as their purpose in life, but while people with this personality type can be found engaging rescue efforts and doing charity work, their real passion is to get to the heart of the issue so that people need not be rescued at all\",\"Advocate indeed share a unique combination of traits: though soft-spoken, they have very strong opinions and will fight tirelessly for an idea they believe in\",\"Advocate are decisive and strong-willed, but will rarely use that energy for personal gain  advocate will act with creativity, imagination, conviction and sensitivity not to create advantage, but to create balance\"]', '1',    '2019-02-06 13:31:00',  '2019-02-07 13:28:44'),
(11,    '1,2,3',    '3,1,2',    '2',    '[\"Consultant personality type are, for lack of a better word, popular  which makes sense, given that it is also a very common personality type, making up twelve percent of the population\",\"Consultant are the cheerleaders and the quarterbacks, setting the tone, taking the spotlight and leading their teams forward to victory and fame\",\"Consultant continue to enjoy supporting their friends and loved ones, organizing social gatherings and doing their best to make sure everyone is happy\",\"Consultant personalities are social creatures, and thrive on staying up to date with what their friends are doing\"]',        '1',    '2019-02-06 13:31:05',  '2019-02-07 13:31:05'),
(12,    '1,2,3',    '3,2,1',    '2',    '[\"Diplomats looking for the hint of good in even the worst of people and events, searching for ways to make things better\",\"Diplomats qualities enable INFPs to communicate deeply with others, easily speaking in metaphors and parables, and understanding and creating symbols to share their ideas\",\"Diplomats have a talent for self-expression, revealing their beauty and their secrets through metaphors and fictional characters\",\"Diplomats communication also lends itself well to INFPs desire for harmony, a recurring theme with Diplomats, and helps them to move forward as they find their calling\"]',   '1',    '2019-02-06 13:31:10',  '2019-02-07 13:33:52'),
(13,    '1,2,3',    '4,1,1',    '2',    '[\"Executive are representatives of tradition and order, utilizing their understanding of what is right, wrong and socially acceptable to bring families and communities together\",\"Executive personalities lead by example, demonstrating dedication and purposeful honesty, and an utter rejection of laziness and cheating, especially in work\",\"Executive declares hard, manual work to be an excellent way to build character\",\"Executive aware of their surroundings and live in a world of clear, verifiable facts  the surety of their knowledge means that even against heavy resistance, they stick to their principles and push an unclouded vision of what is and is not acceptable\"]',    '1',    '2019-02-06 13:31:15',  '2019-02-07 13:36:17'),
(14,    '1,2,3',    '1,5,9',    '5',    '[\"Architect lonely at the top, and being one of the rarest and most strategically capable personality types.\",\"Architect form just two percent of the population, and women of this personality type are especially rare, forming just 0.8% of the population.\",\"Architect enjoy sharing what they know as well, confident in their mastery of their chosen subjects.\",\"Architect at times it will seem that architect are bent on deconstructing and rebuilding every idea and system they come into contact with, employing a sense of perfectionism and even morality to this work.\"]', '1',    '2019-02-07 12:59:25',  '2019-02-07 13:37:57'),
(15,    '1,2,3',    '1,10,10',  '7',    '[\"Good Job\"]',   '1',    '2019-02-08 10:34:50',  '2019-02-08 10:34:50');
             ");

        DB::unprepared("
             INSERT INTO `fi_parent_over_all_interpretations` (`id`, `category_ids`, `individual_range_ids`, `overall_range`, `interpretation`, `status`, `created_at`, `updated_at`) VALUES
(1, '1,2,3',    '1,1,1',    '1',    '[\"Architect lonely at the top, and being one of the rarest and most strategically capable personality types.\",\"Architect form just two percent of the population, and women of this personality type are especially rare, forming just 0.8% of the population.\",\"Architect enjoy sharing what they know as well, confident in their mastery of their chosen subjects.\",\"Architect at times it will seem that architect are bent on deconstructing and rebuilding every idea and system they come into contact with, employing a sense of perfectionism and even morality to this work.\"]', '1',    '2019-02-06 12:22:53',  '2019-02-07 12:45:48'),
(2, '1,2,3',    '6,3,3',    '4',    '[\"Logician personality type is fairly rare, making up only three percent of the population, which is definitely a good thing for them\",\"Logician are known for their brilliant theories and unrelenting logic  in fact, they are considered the most logically precise of all the personality types\",\"Logician may appear to drift about in an unending daydream, but INTPs thought process is unceasing, and their minds buzz with ideas from the moment they wake up\",\"Logician personalities are so prone to reassessing their own thoughts and theories, worrying that theyve missed some critical piece of the puzzle, that they can stagnate, lost in an intangible world where their thoughts are never truly applied\"]',    '1',    '2019-02-06 12:53:54',  '2019-02-07 12:57:39'),
(3, '1,2,3',    '3,6,3',    '4',    '[\"Commander with this personality type embody the gifts of charisma and confidence, and project authority in a way that draws crowds together behind a common goal.\",\"Commander emotional expression isn\\u2019t the strong suit of any Analyst type, but because of their Extraverted (E) nature, commander distance from their emotions is especially public, and felt directly by a much broader swath of people\",\"Commander need to remember though, that their stature comes not just from their own actions, but from the actions of the team that props them up, and that it\\u2019s important to recognize the contributions\",\"Commander will be rewarded with deep, satisfying relationships and all the challenging victories they can handle\"]',    '1',    '2019-02-06 12:54:43',  '2019-02-07 13:04:58'),
(4, '1,2,3',    '1,1,4',    '2',    '[\"Debater personality type is the ultimate devils advocate, thriving on the process of shredding arguments and beliefs and letting the ribbons drift in the wind for all to see\",\"Debater capacity for debate can be a vexing one  while often appreciated when its called for, it can fall painfully flat when they step on others toes by say, openly questioning their boss in a meeting, or picking apart everything their significant other says\",\"Debater intellectual independence and free-form vision are tremendously valuable when theyre in charge, or at least have the ear of someone\",\"Debater people with this personality type may find that the most complex and rewarding intellectual challenge is to understand a more sentimental perspective, and to argue consideration and compromise alongside logic and progress\"]',   '1',    '2019-02-06 13:28:49',  '2019-02-07 13:08:32'),
(5, '1,2,3',    '1,2,3',    '2',    '[\"Mediator personalities are true idealists, always looking for the hint of good in even the worst of people and events, searching for ways to make things better\",\"Mediator comprising just 4% of the population, the risk of feeling misunderstood is unfortunately high for the INFP personality type  but when they find like-minded people to spend their time with, the harmony they feel will be a fountain of joy and inspiration\",\"Mediator qualities enable INFPs to communicate deeply with others, easily speaking in metaphors and parables, and understanding and creating symbols to share their ideas\",\"Mediator strength of this intuitive communication style lends itself well to creative works, and it comes as no surprise that many famous INFPs are poets, writers and actors\"]', '1',    '2019-02-06 13:30:34',  '2019-02-07 13:12:11'),
(6, '1,2,3',    '1,3,2',    '2',    '[\"Enterperneur personality types always have an impact on their immediate surroundings  the best way to spot them at a party is to look for the whirling eddy of people flitting about them as they move from group to group\",\"Enterperneur laughing and entertaining with a blunt and earthy humor, ESTP personalities love to be the center of attention\",\"Enterperneur is an audience member is asked to come on stage, ESTPs volunteer  or volunteer a shy friend\",\"Enterperneur leap before they look, fixing their mistakes as they go, rather than sitting idle, preparing contingencies and escape clauses\"]',   '1',    '2019-02-06 13:30:40',  '2019-02-07 13:15:00'),
(7, '1,2,3',    '1,4,1',    '2',    '[\"Adventurer personality types are true artists, but not necessarily in the typical sense where theyre out painting happy little trees. Often enough though, they are perfectly capable of this\",\"Adventurer enjoy upsetting traditional expectations with experiments in beauty and behavior  chances are, theyve expressed more than once the phrase \'Dont box me in!\'\",\"Adventurer live in a colorful, sensual world, inspired by connections with people and ideas\",\"Adventurer personalities take joy in reinterpreting these connections, reinventing and experimenting with both themselves and new perspectives\"]',  '1',    '2019-02-06 13:30:45',  '2019-02-07 13:18:17'),
(8, '1,2,3',    '2,1,3',    '2',    '[\"Entertrainer is to be found spontaneously breaking into song and dance, it is the Entertrainer personality type\",\"Entertrainer get caught up in the excitement of the moment, and want everyone else to feel that way, too\",\"Entertrainer enjoy the simplest things, and theres no greater joy for them than just having fun with a good group of friends\",\"Entertrainer  rely on luck or opportunity, or simply ask for help from their extensive circle of friends\"]',    '1',    '2019-02-06 13:30:50',  '2019-02-07 13:21:03'),
(9, '1,2,3',    '2,2,2',    '2',    '[\"Defender personality type is quite unique, as many of their qualities defy the definition of their individual traits\",\"Defender possessing the Feeling (F) trait, Defender have excellent analytical abilities; though Introverted (I), they have well-developed people skills and robust social relationships\",\"Defender are true altruists, meeting kindness with kindness-in-excess and engaging the work and people they believe in with enthusiasm and generosity\",\"Defender need to know when to say no and stand up for themselves if they are to maintain their confidence and enthusiasm\"]',    '1',    '2019-02-06 13:30:55',  '2019-02-07 13:23:49'),
(10,    '1,2,3',    '2,3,1',    '2',    '[\"Advocate personality type is very rare, making up less than one percent of the population, but they nonetheless leave their mark on the world\",\"Advocate have an inborn sense of idealism and morality, but what sets them apart is the accompanying Judging trait\",\"Advocate tend to see helping others as their purpose in life, but while people with this personality type can be found engaging rescue efforts and doing charity work, their real passion is to get to the heart of the issue so that people need not be rescued at all\",\"Advocate indeed share a unique combination of traits: though soft-spoken, they have very strong opinions and will fight tirelessly for an idea they believe in\",\"Advocate are decisive and strong-willed, but will rarely use that energy for personal gain  advocate will act with creativity, imagination, conviction and sensitivity not to create advantage, but to create balance\"]', '1',    '2019-02-06 13:31:00',  '2019-02-07 13:28:44'),
(11,    '1,2,3',    '3,1,2',    '2',    '[\"Consultant personality type are, for lack of a better word, popular  which makes sense, given that it is also a very common personality type, making up twelve percent of the population\",\"Consultant are the cheerleaders and the quarterbacks, setting the tone, taking the spotlight and leading their teams forward to victory and fame\",\"Consultant continue to enjoy supporting their friends and loved ones, organizing social gatherings and doing their best to make sure everyone is happy\",\"Consultant personalities are social creatures, and thrive on staying up to date with what their friends are doing\"]',        '1',    '2019-02-06 13:31:05',  '2019-02-07 13:31:05'),
(12,    '1,2,3',    '3,2,1',    '2',    '[\"Diplomats looking for the hint of good in even the worst of people and events, searching for ways to make things better\",\"Diplomats qualities enable INFPs to communicate deeply with others, easily speaking in metaphors and parables, and understanding and creating symbols to share their ideas\",\"Diplomats have a talent for self-expression, revealing their beauty and their secrets through metaphors and fictional characters\",\"Diplomats communication also lends itself well to INFPs desire for harmony, a recurring theme with Diplomats, and helps them to move forward as they find their calling\"]',   '1',    '2019-02-06 13:31:10',  '2019-02-07 13:33:52'),
(13,    '1,2,3',    '4,1,1',    '2',    '[\"Executive are representatives of tradition and order, utilizing their understanding of what is right, wrong and socially acceptable to bring families and communities together\",\"Executive personalities lead by example, demonstrating dedication and purposeful honesty, and an utter rejection of laziness and cheating, especially in work\",\"Executive declares hard, manual work to be an excellent way to build character\",\"Executive aware of their surroundings and live in a world of clear, verifiable facts  the surety of their knowledge means that even against heavy resistance, they stick to their principles and push an unclouded vision of what is and is not acceptable\"]',    '1',    '2019-02-06 13:31:15',  '2019-02-07 13:36:17'),
(14,    '1,2,3',    '1,5,9',    '5',    '[\"Architect lonely at the top, and being one of the rarest and most strategically capable personality types.\",\"Architect form just two percent of the population, and women of this personality type are especially rare, forming just 0.8% of the population.\",\"Architect enjoy sharing what they know as well, confident in their mastery of their chosen subjects.\",\"Architect at times it will seem that architect are bent on deconstructing and rebuilding every idea and system they come into contact with, employing a sense of perfectionism and even morality to this work.\"]', '1',    '2019-02-07 12:59:25',  '2019-02-07 13:37:57'),
(15,    '1,2,3',    '1,10,10',  '7',    '[\"Good Job\"]',   '1',    '2019-02-08 10:34:50',  '2019-02-08 10:34:50');
             ");

        DB::unprepared("
             INSERT INTO `fi_category_wise_interpretation` (`id`, `category_id`, `range_id`, `interpretation`, `status`, `created_at`, `updated_at`) VALUES
(1, 1,  1,  '[\"People with the INTJ personality type are imaginative yet decisive, ambitious yet private, amazingly curious.\",\"While this may be intended as an insult by their peers, they more than likely identify with it and are even proud of it, greatly enjoying their broad and deep body of knowledge.\",\"But this is because INTJ types tend to believe that with effort, intelligence and consideration, nothing is impossible, while at the same time they believe that people are too lazy.\"]',  '1',    '2019-02-06 12:22:05',  '2019-02-08 10:16:01'),
(2, 2,  1,  '[\"ENTJs are natural-born leaders. People with this personality type embody the gifts of charisma and confidence, and project authority in a way that draws crowds together behind a common goal.\",\"But unlike their Feeling (F) counterpart, ENTJs are characterized by an often ruthless level of rationality, using their drive, determination and sharp minds to achieve whatever end they\\u2019ve set for themselves.\",\"Perhaps it is best that they make up only three percent of the population, lest they overwhelm the more timid and sensitive personality types that make up much of the rest of the world.\"]',   '1',    '2019-02-06 12:23:41',  '2019-02-08 10:25:34'),
(3, 3,  1,  '[\"Then step back to let more numerous and fastidious personalities handle the logistics of implementation and maintenance.\",\"ENTPs\\u2019 capacity for debate can be a vexing one \\u2013 while often appreciated when it\\u2019s called for, it can fall painfully flat when they step on others\\u2019 toes by say.\",\"This is further complicated by ENTPs\\u2019 unyielding honesty, as this type doesn\\u2019t mince words and cares little about being seen as sensitive or compassionate.\"]',  '1',    '2019-02-06 12:24:00',  '2019-02-08 10:37:03'),
(4, 1,  2,  '[\"self-confidence and an aura of mystery, and their insightful observations, original ideas and formidable logic enable them to push change through with sheer willpower and force of personality.\",\"They will strive to remain rational no matter how attractive the end goal may be, and every idea, whether generated internally or soaked in from the outside world\",\"They are brilliant and confident in bodies of knowledge they have taken the time to understand, but unfortunately the social contract is unlikely to be one of those subjects.\"]', '1',    '2019-02-06 12:59:57',  '2019-02-08 10:17:35'),
(5, 1,  3,  '[\"They work with the familiar can serve as its own beacon, attracting people, romantically or otherwise, of similar temperament and interests.\",\"They are defined by their tendency to move through life as though it were a giant chess board, pieces constantly shifting with consideration and intelligence.\",\"Constantly outmaneuvering their peers in order to maintain control of a situation while maximizing their freedom to move about.\"]',    '1',    '2019-02-06 13:00:10',  '2019-02-08 10:18:34'),
(6, 1,  4,  '[\"Personality type is fairly rare, making up only three percent of the population, which is definitely a good thing for them,\",\"Pride themselves on their inventiveness and creativity, their unique perspective and vigorous intellect.\",\"They have been responsible for many scientific discoveries throughout history.\"]',    '1',    '2019-02-06 13:00:25',  '2019-02-08 10:19:29'),
(7, 1,  5,  '[\"They love patterns, and spotting discrepancies between statements could almost be described as a hobby, making it a bad idea to lie to an INTP.\",\"But people with the INTP personality type tend to share thoughts that are not fully developed.\",\"Using others as a sounding board for ideas and theories in a debate against themselves rather than as actual conversation partners.\"]', '1',    '2019-02-06 13:00:36',  '2019-02-08 10:20:27'),
(8, 1,  6,  '[\"This may make them appear unreliable, but in reality no one is more enthusiastic and capable of spotting a problem, drilling through the endless factors and details .\",\"People who share the INTP personality type aren\\u2019t interested in practical, day-to-day activities and maintenance.\",\"There is no limit to the time and energy INTPs will expend in developing an insightful and unbiased solution.\"]',   '1',    '2019-02-06 13:00:48',  '2019-02-08 10:21:23'),
(9, 1,  7,  '[\"They may appear to drift about in an unending daydream, but INTPs\\u2019 thought process is unceasing, and their minds buzz with ideas from the moment they wake up.\",\"This constant thinking can have the effect of making them look pensive and detached, as they are often conducting full-fledged debates in their own heads.\",\"INTP personalities are among unfamiliar faces, and friendly banter can quickly become combative if they believe their logical conclusions or theories are being criticized.\"]',    '1',    '2019-02-06 13:00:58',  '2019-02-08 10:22:21'),
(10,    1,  8,  '[\"When INTPs are particularly excited, the conversation can border on incoherence as they try to explain the daisy-chain of logical conclusions that led to the formation of their latest idea\",\"Oftentimes, INTPs will opt to simply move on from a topic before it\\u2019s ever understood what they were trying to say, rather than try to lay things out in plain terms.\",\"The reverse can also be true when people explain their thought processes to INTPs in terms of subjectivity and feeling. Imagine an immensely complicated clockwork.\"]',   '1',    '2019-02-06 13:01:12',  '2019-02-08 10:22:49'),
(11,    1,  9,  '[\"INTPs are unlikely to understand emotional complaints at all, and their friends won\\u2019t find a bedrock of emotional support in them.\",\"People with the INTP personality type would much rather make a series of logical suggestions for how to resolve the underlying issue, a perspective that is not always welcomed by their Feeling (F) companions.\",\"This will likely extend to most social conventions and goals as well, like planning dinners and getting married, as INTPs are far more concerned with originality and efficient results.\"]', '1',    '2019-02-06 13:01:28',  '2019-02-08 10:23:28'),
(12,    1,  10, '[\"The one thing that really holds INTPs back is their restless and pervasive fear of failure.\",\"INTP personalities are so prone to reassessing their own thoughts and theories, worrying that they\\u2019ve missed some critical piece of the puzzle.\",\"Overcoming this self-doubt stands as the greatest challenge INTPs are likely to face, but the intellectual gifts \\u2013 big and small \\u2013 bestowed on the world when they do makes it worth the fight.\"]',  '1',    '2019-02-06 13:01:40',  '2019-02-08 10:24:24'),
(13,    2,  2,  '[\"If there\\u2019s anything ENTJs love, it\\u2019s a good challenge, big or small, and they firmly believe that given enough time and resources, they can achieve any goal.\",\"This quality makes people with the ENTJ personality type brilliant entrepreneurs.\",\"This determination is often a self-fulfilling prophecy, as ENTJs push their goals through with sheer willpower where others might give up and move on.\"]', '1',    '2019-02-06 13:01:54',  '2019-02-08 10:27:07'),
(14,    2,  3,  '[\"At the negotiating table, be it in a corporate environment or buying a car, ENTJs are dominant, relentless, and unforgiving.\",\"This isn\\u2019t because they are coldhearted or vicious per se \\u2013 it\\u2019s more that ENTJ personalities genuinely enjoy the challenge.\",\"The battle of wits, the repartee that comes from this environment, and if the other side can\\u2019t keep up, that\\u2019s no reason for ENTJs to fold on their own core tenet of ultimate victory.\"]',    '1',    '2019-02-06 13:02:03',  '2019-02-08 10:28:00'),
(15,    2,  4,  '[\"If there\\u2019s anyone ENTJs respect, it\\u2019s someone who is able to stand up to them intellectually, who is able to act with a precision and quality equal to their own.\",\"ENTJ personalities have a particular skill in recognizing the talents of others, and this helps in both their team-building efforts.\",\"However, they also have a particular skill in calling out others\\u2019 failures with a chilling degree of insensitivity, and this is where ENTJs really start to run into trouble.\"]', '1',    '2019-02-06 13:02:14',  '2019-02-08 10:28:50'),
(16,    2,  5,  '[\"Emotional expression isn\\u2019t the strong suit of any Analyst type, but because of their Extraverted (E) nature, ENTJs\\u2019 distance from their emotions is especially public.\",\"Especially in a professional environment, ENTJs will simply crush the sensitivities of those they view as inefficient, incompetent or lazy.\",\"To people with the ENTJ personality type, emotional displays are displays of weakness, and it\\u2019s easy to make enemies with this approach.\"]',  '1',    '2019-02-06 13:02:26',  '2019-02-08 10:29:28'),
(17,    2,  6,  '[\"ENTJs will do well to remember that they absolutely depend on having a functioning team, not just to achieve their goals.\",\"But for their validation and feedback as well, something ENTJs are, curiously, very sensitive to.\",\"ENTJs are true powerhouses, and they cultivate an image of being larger than life \\u2013 and often enough they are\"]',    '1',    '2019-02-06 13:02:36',  '2019-02-08 10:30:08'),
(18,    2,  7,  '[\"They need to remember though, that their stature comes not just from their own actions, but from the actions of the team that props them up\",\"Even if they have to adopt a \\\"fake it \\u2018til you make it\\\" mentality, if ENTJs are able to combine an emotionally healthy focus alongside their many strengths.\",\"They will be rewarded with deep, satisfying relationships and all the challenging victories they can handle.\"]',  '1',    '2019-02-06 13:02:47',  '2019-02-08 10:30:58'),
(19,    2,  8,  '[\"The ENTP personality type is the ultimate devil\\u2019s advocate, thriving on the process of shredding arguments and beliefs and letting the ribbons drift in the wind for all to see.\",\"ENTPs don\\u2019t do this because they are trying to achieve some deeper purpose or strategic goal, but for the simple reason that it\\u2019s fun.\",\"No one loves the process of mental sparring more than ENTPs, as it gives them a chance to exercise their effortlessly quick wit, broad accumulated knowledge base.\"]',   '1',    '2019-02-06 13:02:59',  '2019-02-08 10:34:20'),
(20,    2,  9,  '[\"Playing the devil\\u2019s advocate helps people with the ENTP personality type to not only develop a better sense of others\\u2019 reasoning, but a better understanding of opposing ideas.\",\"This tactic shouldn\\u2019t be confused with the sort of mutual understanding Diplomats seek \\u2013 ENTPs, like all Analyst personality types, are on a constant quest for knowledge\",\"Taking a certain pleasure in being the underdog, ENTPs enjoy the mental exercise found in questioning the prevailing mode of thought, making them irreplaceable in reworking existing systems or shaking things up and pushing them in clever new directions.\"]',    '1',    '2019-02-06 13:03:10',  '2019-02-08 10:35:07'),
(21,    2,  10, '[\"However, they\\u2019ll be miserable managing the day-to-day mechanics of actually implementing their suggestions.\",\"ENTP personalities love to brainstorm and think big, but they will avoid getting caught doing the \\\"grunt work\\\" at all costs.\",\"ENTPs only make up about three percent of the population, which is just right, as it lets them create original ideas.\"]', '1',    '2019-02-06 13:03:21',  '2019-02-08 10:36:00'),
(22,    3,  2,  '[\"Likeminded types get along well enough with people with the ENTP personality type, but more sensitive types.\",\"They are often conflict-averse, preferring feelings, comfort, and even white lies over unpleasant truths and hard rationality.\",\"This frustrates ENTPs, and they find that their quarrelsome fun burns many bridges, oftentimes inadvertently, as they plow through others\\u2019 thresholds for having their beliefs questioned and their feelings brushed aside\"]',   '1',    '2019-02-06 13:03:42',  '2019-02-08 10:38:14'),
(23,    3,  3,  '[\"Treating others as they\\u2019d be treated, ENTPs have little tolerance for being coddled, and dislike when people beat around the bush.\",\"ENTP personalities find themselves respected for their vision, confidence, knowledge, and keen sense of humor.\",\"But often struggle to utilize these qualities as the basis for deeper friendships and romantic relationships\"]',   '1',    '2019-02-06 13:03:52',  '2019-02-08 10:39:03'),
(24,    3,  4,  '[\"ENTPs have a longer road than most in harnessing their natural abilities \\u2013 their intellectual independence and free-form vision are tremendously valuable when they\\u2019re in charge.\",\"Or at least have the ear of someone who is, but getting there can take a level of follow-through that ENTPs struggle with.\",\"Once they\\u2019ve secured such a position, ENTPs need to remember that for their ideas to come to fruition, they will always depend on others to assemble the pieces\"]', '1',    '2019-02-06 13:04:05',  '2019-02-08 10:39:34'),
(25,    3,  5,  '[\"If they\\u2019ve spent more time  \winning\ arguments than they have building consensus, many ENTPs will find they simply don\\u2019t have the support necessary to be successful\",\"Playing devil\\u2019s advocate so well, people with this personality type may find that the most complex and rewarding intellectual challenge is to understand a more sentimental perspective.\",\"ENTPs only make up about three percent of the population, which is just right, as it lets them create original ideas.\"]',    '1',    '2019-02-06 13:04:12',  '2019-02-08 10:40:17'),
(26,    3,  6,  '[\"This personality type is very rare, making up less than one percent of the population, but they nonetheless leave their mark on the world.\",\"Tend to see helping others as their purpose in life, but while people with this personality type can be found engaging rescue efforts and doing charity work.\",\"Indeed share a unique combination of traits: though soft-spoken, they have very strong opinions and will fight tirelessly for an idea they believe in.\"]',    '1',    '2019-02-06 13:04:21',  '2019-02-08 10:42:14'),
(27,    3,  7,  '[\"They are decisive and strong-willed, but will rarely use that energy for personal gain \\u2013 INFJs will act with creativity, imagination.\",\"Conviction and sensitivity not to create advantage, but to create balance. Egalitarianism and karma are very attractive ideas .\",\"They tend to believe that nothing would help the world so much as using love and compassion to soften the hearts of tyrants.\"]',   '1',    '2019-02-06 13:04:35',  '2019-02-08 10:43:15'),
(28,    3,  8,  '[\"Easy to make connections with others, and have a talent for warm, sensitive language, speaking in human terms, rather than with pure logic and fact\",\"It makes sense that their friends and colleagues will come to think of them as quiet Extraverted types.\",\"Take great care of other\\u2019s feelings, and they expect the favor to be returned \\u2013 sometimes that means giving them the space they need for a few days.\"]',   '1',    '2019-02-06 13:05:00',  '2019-02-08 10:44:05'),
(29,    3,  9,  '[\"It is most important for INFJs to remember to take care of themselves. The passion of their convictions is perfectly capable of carrying them past their breaking point and if their zeal gets out of hand\",\"But when the circumstances are unavoidable, they can fight back in highly irrational, unhelpful ways\",\"The world is a place full of inequity \\u2013 but it doesn\\u2019t have to be. No other personality type is better suited to create a movement to right a wrong, no matter how big or small.\",\"Just need to remember that while they\\u2019re busy taking care of the world, they need to take care of themselves, too.\"]',  '1',    '2019-02-06 13:05:13',  '2019-02-08 10:45:10'),
(30,    3,  10, '[\"They representatives of tradition and order, utilizing their understanding of what is right, wrong and socially acceptable to bring families and communities together\",\"Taking pride in bringing people together, ESTJs often take on roles as community organizers.\",\"Working hard to bring everyone together in celebration of cherished local events, or in defense of the traditional values that hold families and communities together.\"]',  '1',    '2019-02-06 13:05:22',  '2019-02-08 10:45:59');
 ");

        DB::unprepared("
         
             INSERT INTO `fi_parent_category_wise_interpretation` (`id`, `category_id`, `range_id`, `interpretation`, `status`, `created_at`, `updated_at`) VALUES
(1, 1,  1,  '[\"People with the INTJ personality type are imaginative yet decisive, ambitious yet private, amazingly curious.\",\"While this may be intended as an insult by their peers, they more than likely identify with it and are even proud of it, greatly enjoying their broad and deep body of knowledge.\",\"But this is because INTJ types tend to believe that with effort, intelligence and consideration, nothing is impossible, while at the same time they believe that people are too lazy.\"]',  '1',    '2019-02-06 12:22:05',  '2019-02-08 10:16:01'),
(2, 2,  1,  '[\"ENTJs are natural-born leaders. People with this personality type embody the gifts of charisma and confidence, and project authority in a way that draws crowds together behind a common goal.\",\"But unlike their Feeling (F) counterpart, ENTJs are characterized by an often ruthless level of rationality, using their drive, determination and sharp minds to achieve whatever end they\\u2019ve set for themselves.\",\"Perhaps it is best that they make up only three percent of the population, lest they overwhelm the more timid and sensitive personality types that make up much of the rest of the world.\"]',   '1',    '2019-02-06 12:23:41',  '2019-02-08 10:25:34'),
(3, 3,  1,  '[\"Then step back to let more numerous and fastidious personalities handle the logistics of implementation and maintenance.\",\"ENTPs\\u2019 capacity for debate can be a vexing one \\u2013 while often appreciated when it\\u2019s called for, it can fall painfully flat when they step on others\\u2019 toes by say.\",\"This is further complicated by ENTPs\\u2019 unyielding honesty, as this type doesn\\u2019t mince words and cares little about being seen as sensitive or compassionate.\"]',  '1',    '2019-02-06 12:24:00',  '2019-02-08 10:37:03'),
(4, 1,  2,  '[\"self-confidence and an aura of mystery, and their insightful observations, original ideas and formidable logic enable them to push change through with sheer willpower and force of personality.\",\"They will strive to remain rational no matter how attractive the end goal may be, and every idea, whether generated internally or soaked in from the outside world\",\"They are brilliant and confident in bodies of knowledge they have taken the time to understand, but unfortunately the social contract is unlikely to be one of those subjects.\"]', '1',    '2019-02-06 12:59:57',  '2019-02-08 10:17:35'),
(5, 1,  3,  '[\"They work with the familiar can serve as its own beacon, attracting people, romantically or otherwise, of similar temperament and interests.\",\"They are defined by their tendency to move through life as though it were a giant chess board, pieces constantly shifting with consideration and intelligence.\",\"Constantly outmaneuvering their peers in order to maintain control of a situation while maximizing their freedom to move about.\"]',    '1',    '2019-02-06 13:00:10',  '2019-02-08 10:18:34'),
(6, 1,  4,  '[\"Personality type is fairly rare, making up only three percent of the population, which is definitely a good thing for them,\",\"Pride themselves on their inventiveness and creativity, their unique perspective and vigorous intellect.\",\"They have been responsible for many scientific discoveries throughout history.\"]',    '1',    '2019-02-06 13:00:25',  '2019-02-08 10:19:29'),
(7, 1,  5,  '[\"They love patterns, and spotting discrepancies between statements could almost be described as a hobby, making it a bad idea to lie to an INTP.\",\"But people with the INTP personality type tend to share thoughts that are not fully developed.\",\"Using others as a sounding board for ideas and theories in a debate against themselves rather than as actual conversation partners.\"]', '1',    '2019-02-06 13:00:36',  '2019-02-08 10:20:27'),
(8, 1,  6,  '[\"This may make them appear unreliable, but in reality no one is more enthusiastic and capable of spotting a problem, drilling through the endless factors and details .\",\"People who share the INTP personality type aren\\u2019t interested in practical, day-to-day activities and maintenance.\",\"There is no limit to the time and energy INTPs will expend in developing an insightful and unbiased solution.\"]',   '1',    '2019-02-06 13:00:48',  '2019-02-08 10:21:23'),
(9, 1,  7,  '[\"They may appear to drift about in an unending daydream, but INTPs\\u2019 thought process is unceasing, and their minds buzz with ideas from the moment they wake up.\",\"This constant thinking can have the effect of making them look pensive and detached, as they are often conducting full-fledged debates in their own heads.\",\"INTP personalities are among unfamiliar faces, and friendly banter can quickly become combative if they believe their logical conclusions or theories are being criticized.\"]',    '1',    '2019-02-06 13:00:58',  '2019-02-08 10:22:21'),
(10,    1,  8,  '[\"When INTPs are particularly excited, the conversation can border on incoherence as they try to explain the daisy-chain of logical conclusions that led to the formation of their latest idea\",\"Oftentimes, INTPs will opt to simply move on from a topic before it\\u2019s ever understood what they were trying to say, rather than try to lay things out in plain terms.\",\"The reverse can also be true when people explain their thought processes to INTPs in terms of subjectivity and feeling. Imagine an immensely complicated clockwork.\"]',   '1',    '2019-02-06 13:01:12',  '2019-02-08 10:22:49'),
(11,    1,  9,  '[\"INTPs are unlikely to understand emotional complaints at all, and their friends won\\u2019t find a bedrock of emotional support in them.\",\"People with the INTP personality type would much rather make a series of logical suggestions for how to resolve the underlying issue, a perspective that is not always welcomed by their Feeling (F) companions.\",\"This will likely extend to most social conventions and goals as well, like planning dinners and getting married, as INTPs are far more concerned with originality and efficient results.\"]', '1',    '2019-02-06 13:01:28',  '2019-02-08 10:23:28'),
(12,    1,  10, '[\"The one thing that really holds INTPs back is their restless and pervasive fear of failure.\",\"INTP personalities are so prone to reassessing their own thoughts and theories, worrying that they\\u2019ve missed some critical piece of the puzzle.\",\"Overcoming this self-doubt stands as the greatest challenge INTPs are likely to face, but the intellectual gifts \\u2013 big and small \\u2013 bestowed on the world when they do makes it worth the fight.\"]',  '1',    '2019-02-06 13:01:40',  '2019-02-08 10:24:24'),
(13,    2,  2,  '[\"If there\\u2019s anything ENTJs love, it\\u2019s a good challenge, big or small, and they firmly believe that given enough time and resources, they can achieve any goal.\",\"This quality makes people with the ENTJ personality type brilliant entrepreneurs.\",\"This determination is often a self-fulfilling prophecy, as ENTJs push their goals through with sheer willpower where others might give up and move on.\"]', '1',    '2019-02-06 13:01:54',  '2019-02-08 10:27:07'),
(14,    2,  3,  '[\"At the negotiating table, be it in a corporate environment or buying a car, ENTJs are dominant, relentless, and unforgiving.\",\"This isn\\u2019t because they are coldhearted or vicious per se \\u2013 it\\u2019s more that ENTJ personalities genuinely enjoy the challenge.\",\"The battle of wits, the repartee that comes from this environment, and if the other side can\\u2019t keep up, that\\u2019s no reason for ENTJs to fold on their own core tenet of ultimate victory.\"]',    '1',    '2019-02-06 13:02:03',  '2019-02-08 10:28:00'),
(15,    2,  4,  '[\"If there\\u2019s anyone ENTJs respect, it\\u2019s someone who is able to stand up to them intellectually, who is able to act with a precision and quality equal to their own.\",\"ENTJ personalities have a particular skill in recognizing the talents of others, and this helps in both their team-building efforts.\",\"However, they also have a particular skill in calling out others\\u2019 failures with a chilling degree of insensitivity, and this is where ENTJs really start to run into trouble.\"]', '1',    '2019-02-06 13:02:14',  '2019-02-08 10:28:50'),
(16,    2,  5,  '[\"Emotional expression isn\\u2019t the strong suit of any Analyst type, but because of their Extraverted (E) nature, ENTJs\\u2019 distance from their emotions is especially public.\",\"Especially in a professional environment, ENTJs will simply crush the sensitivities of those they view as inefficient, incompetent or lazy.\",\"To people with the ENTJ personality type, emotional displays are displays of weakness, and it\\u2019s easy to make enemies with this approach.\"]',  '1',    '2019-02-06 13:02:26',  '2019-02-08 10:29:28'),
(17,    2,  6,  '[\"ENTJs will do well to remember that they absolutely depend on having a functioning team, not just to achieve their goals.\",\"But for their validation and feedback as well, something ENTJs are, curiously, very sensitive to.\",\"ENTJs are true powerhouses, and they cultivate an image of being larger than life \\u2013 and often enough they are\"]',    '1',    '2019-02-06 13:02:36',  '2019-02-08 10:30:08'),
(18,    2,  7,  '[\"They need to remember though, that their stature comes not just from their own actions, but from the actions of the team that props them up\",\"Even if they have to adopt a \\\"fake it \\u2018til you make it\\\" mentality, if ENTJs are able to combine an emotionally healthy focus alongside their many strengths.\",\"They will be rewarded with deep, satisfying relationships and all the challenging victories they can handle.\"]',  '1',    '2019-02-06 13:02:47',  '2019-02-08 10:30:58'),
(19,    2,  8,  '[\"The ENTP personality type is the ultimate devil\\u2019s advocate, thriving on the process of shredding arguments and beliefs and letting the ribbons drift in the wind for all to see.\",\"ENTPs don\\u2019t do this because they are trying to achieve some deeper purpose or strategic goal, but for the simple reason that it\\u2019s fun.\",\"No one loves the process of mental sparring more than ENTPs, as it gives them a chance to exercise their effortlessly quick wit, broad accumulated knowledge base.\"]',   '1',    '2019-02-06 13:02:59',  '2019-02-08 10:34:20'),
(20,    2,  9,  '[\"Playing the devil\\u2019s advocate helps people with the ENTP personality type to not only develop a better sense of others\\u2019 reasoning, but a better understanding of opposing ideas.\",\"This tactic shouldn\\u2019t be confused with the sort of mutual understanding Diplomats seek \\u2013 ENTPs, like all Analyst personality types, are on a constant quest for knowledge\",\"Taking a certain pleasure in being the underdog, ENTPs enjoy the mental exercise found in questioning the prevailing mode of thought, making them irreplaceable in reworking existing systems or shaking things up and pushing them in clever new directions.\"]',    '1',    '2019-02-06 13:03:10',  '2019-02-08 10:35:07'),
(21,    2,  10, '[\"However, they\\u2019ll be miserable managing the day-to-day mechanics of actually implementing their suggestions.\",\"ENTP personalities love to brainstorm and think big, but they will avoid getting caught doing the \\\"grunt work\\\" at all costs.\",\"ENTPs only make up about three percent of the population, which is just right, as it lets them create original ideas.\"]', '1',    '2019-02-06 13:03:21',  '2019-02-08 10:36:00'),
(22,    3,  2,  '[\"Likeminded types get along well enough with people with the ENTP personality type, but more sensitive types.\",\"They are often conflict-averse, preferring feelings, comfort, and even white lies over unpleasant truths and hard rationality.\",\"This frustrates ENTPs, and they find that their quarrelsome fun burns many bridges, oftentimes inadvertently, as they plow through others\\u2019 thresholds for having their beliefs questioned and their feelings brushed aside\"]',   '1',    '2019-02-06 13:03:42',  '2019-02-08 10:38:14'),
(23,    3,  3,  '[\"Treating others as they\\u2019d be treated, ENTPs have little tolerance for being coddled, and dislike when people beat around the bush.\",\"ENTP personalities find themselves respected for their vision, confidence, knowledge, and keen sense of humor.\",\"But often struggle to utilize these qualities as the basis for deeper friendships and romantic relationships\"]',   '1',    '2019-02-06 13:03:52',  '2019-02-08 10:39:03'),
(24,    3,  4,  '[\"ENTPs have a longer road than most in harnessing their natural abilities \\u2013 their intellectual independence and free-form vision are tremendously valuable when they\\u2019re in charge.\",\"Or at least have the ear of someone who is, but getting there can take a level of follow-through that ENTPs struggle with.\",\"Once they\\u2019ve secured such a position, ENTPs need to remember that for their ideas to come to fruition, they will always depend on others to assemble the pieces\"]', '1',    '2019-02-06 13:04:05',  '2019-02-08 10:39:34'),
(25,    3,  5,  '[\"If they\\u2019ve spent more time \\winning\\ arguments than they have building consensus, many ENTPs will find they simply don\\u2019t have the support necessary to be successful\",\"Playing devil\\u2019s advocate so well, people with this personality type may find that the most complex and rewarding intellectual challenge is to understand a more sentimental perspective.\",\"ENTPs only make up about three percent of the population, which is just right, as it lets them create original ideas.\"]',    '1',    '2019-02-06 13:04:12',  '2019-02-08 10:40:17'),
(26,    3,  6,  '[\"This personality type is very rare, making up less than one percent of the population, but they nonetheless leave their mark on the world.\",\"Tend to see helping others as their purpose in life, but while people with this personality type can be found engaging rescue efforts and doing charity work.\",\"Indeed share a unique combination of traits: though soft-spoken, they have very strong opinions and will fight tirelessly for an idea they believe in.\"]',    '1',    '2019-02-06 13:04:21',  '2019-02-08 10:42:14'),
(27,    3,  7,  '[\"They are decisive and strong-willed, but will rarely use that energy for personal gain \\u2013 INFJs will act with creativity, imagination.\",\"Conviction and sensitivity not to create advantage, but to create balance. Egalitarianism and karma are very attractive ideas .\",\"They tend to believe that nothing would help the world so much as using love and compassion to soften the hearts of tyrants.\"]',   '1',    '2019-02-06 13:04:35',  '2019-02-08 10:43:15'),
(28,    3,  8,  '[\"Easy to make connections with others, and have a talent for warm, sensitive language, speaking in human terms, rather than with pure logic and fact\",\"It makes sense that their friends and colleagues will come to think of them as quiet Extraverted types.\",\"Take great care of other\\u2019s feelings, and they expect the favor to be returned \\u2013 sometimes that means giving them the space they need for a few days.\"]',   '1',    '2019-02-06 13:05:00',  '2019-02-08 10:44:05'),
(29,    3,  9,  '[\"It is most important for INFJs to remember to take care of themselves. The passion of their convictions is perfectly capable of carrying them past their breaking point and if their zeal gets out of hand\",\"But when the circumstances are unavoidable, they can fight back in highly irrational, unhelpful ways\",\"The world is a place full of inequity \\u2013 but it doesn\\u2019t have to be. No other personality type is better suited to create a movement to right a wrong, no matter how big or small.\",\"Just need to remember that while they\\u2019re busy taking care of the world, they need to take care of themselves, too.\"]',  '1',    '2019-02-06 13:05:13',  '2019-02-08 10:45:10'),
(30,    3,  10, '[\"They representatives of tradition and order, utilizing their understanding of what is right, wrong and socially acceptable to bring families and communities together\",\"Taking pride in bringing people together, ESTJs often take on roles as community organizers.\",\"Working hard to bring everyone together in celebration of cherished local events, or in defense of the traditional values that hold families and communities together.\"]',  '1',    '2019-02-06 13:05:22',  '2019-02-08 10:45:59');
 ");
    }

}
